FROM debian:buster

ENV MYSQL_ROOT_PASSWORD='root_password' \
    MYSQL_DATABASE='wordpress' \
    MYSQL_USER='wordpress_user' \
    MYSQL_PASSWORD='wordpress_password' \
    DEBIAN_FRONTEND=noninteractive \
    container=docker

# Install MySQL
RUN apt-get update && \
    apt-get install -y mariadb-server && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configure MySQL
RUN mkdir -p /var/run/mysqld /var/lib/mysql && \
    chmod 1777 /var/run/mysqld /var/lib/mysql

VOLUME ["/var/lib/mysql/"]

# Expose port 3306
EXPOSE 3306

RUN service mysql start \
    && mysqladmin -u root password $MYSQL_ROOT_PASSWORD \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};" \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';" \
    && mysql --user=root --password=$MYSQL_ROOT_PASSWORD -e "FLUSH PRIVILEGES;"

# Start MySQL in the foreground
CMD ["mysqld", "--user=mysql", "--console"]
